using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace TodayTask1
{
    class Program
    {
        static void Main(string[] args)
        {
            //로딩바 시작화면
            //게임스토리1
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("많고 많은 초가상현실 게임들 중에서도 가장 인기가 많은 BRG Simulator");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("많고 많은 초가상현실 게임들 중에서도 가장 인기가 많은 BRG Simulator");
            Console.WriteLine("이 게임을 해본 사람들은 모두들 말했다.");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("매일매일이 기대되는 공간");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("매일매일이 기대되는 공간");
            Console.WriteLine("부와 명예를 얻을 수 있는 공간");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("매일매일이 기대되는 공간");
            Console.WriteLine("부와 명예를 얻을 수 있는 공간");
            Console.WriteLine("짜릿한 모험과 자신만의 이야기가 있는 공간");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("매일매일이 기대되는 공간");
            Console.WriteLine("부와 명예를 얻을 수 있는 공간");
            Console.WriteLine("짜릿한 모험과 자신만의 이야기가 있는 공간.");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("매일매일이 기대되는 공간");
            Console.WriteLine("부와 명예를 얻을 수 있는 공간");
            Console.WriteLine("짜릿한 모험과 자신만의 이야기가 있는 공간..");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("매일매일이 기대되는 공간");
            Console.WriteLine("부와 명예를 얻을 수 있는 공간");
            Console.WriteLine("짜릿한 모험과 자신만의 이야기가 있는 공간...");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("' 뿔토끼 잡으실분 파티해요!! '");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("' 법사분 와주세요!!! '");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("' 이벤트 퀘스트 같이 하실 분!!! '");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("문 근처에 선 것만으로도 시끄럽게 안쪽의 소리가 들린다.");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("문 근처에 선 것만으로도 시끄럽게 안쪽의 소리가 들린다.");
            Console.WriteLine("시끌벅적한 이 곳은 선술집");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("문 근처에 선 것만으로도 시끄럽게 안쪽의 소리가 들린다.");
            Console.WriteLine("시끌벅적한 이 곳은 선술집");
            Console.WriteLine("말이 선술집이지 사실상 파티를 찾거나 의뢰를 받는 곳이다.");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("문 근처에 선 것만으로도 시끄럽게 안쪽의 소리가 들린다.");
            Console.WriteLine("시끌벅적한 이 곳은 선술집");
            Console.WriteLine("말이 선술집이지 사실상 파티를 찾거나 의뢰를 받는 곳이다.");
            Console.WriteLine("모험가라면 당연히 자주 들락거리는 장소이지만");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("이곳은...");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("내가 제일 싫어하는 곳이다.");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("'' 으...파티는 싫은대... ''");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("'' 하필이면 이번 이벤트 퀘스트가 파티퀘스트라니..... ''");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("'' 운영자들은 파티 안하는 사람은 배려 안하나?!! ''");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("벌써부터 들어가기 싫어서 화내보지만 어쩔수 없다.");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("벌써부터 들어가기 싫어서 화내보지만 어쩔수 없다.");
            Console.WriteLine("안하고 싶어도 하필이면 퀘스트 보상이 짭짤해서 문제다");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("벌써부터 들어가기 싫어서 화내보지만 어쩔수 없다.");
            Console.WriteLine("안하고 싶어도 하필이면 퀘스트 보상이 짭짤해서 문제다");
            Console.WriteLine("화가 머리 끝까지 났지만 어쩔수없다 보상을 위해서라면 하는 수 밖에");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("'' 그래 그래도 오늘은 좋은 사람들일 수도 있어 ''");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("'' 한명쯤은 극극극F성향 사람 정돈 걸려서 이해해주지 않을까?!! ''");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("말도 안되는 헛된 바람을 가슴에 안으며 선술집으로 들어선다.");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine(".");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("..");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("...");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("{파티에서 강퇴되었습니다.}");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("{파티에서 강퇴되었습니다.}");
            Console.WriteLine("{파티에서 강퇴되었습니다.}");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("{파티에서 강퇴되었습니다.}");
            Console.WriteLine("{파티에서 강퇴되었습니다.}");
            Console.WriteLine("{파티에서 강퇴되었습니다.}");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("' 저기요 이럴꺼면 다시는 파티 할려고 하지마세요 '");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("' 아니 이럴꺼면 왜 하는거야!!!! '");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("' 하아... 저분 빼고 다시 구하죠 '");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("파티만 들어가면 나에게 돌아오는 팀원들의 한숨과 한탄");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("파티만 들어가면 나에게 돌아오는 팀원들의 한숨과 한탄");
            Console.WriteLine("저들이 저러는 것은 내가 게임을 못해서 그런게 아니다");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("파티만 들어가면 나에게 돌아오는 팀원들의 한숨과 한탄");
            Console.WriteLine("저들이 저러는 것은 내가 게임을 못해서 그런게 아니다");
            Console.WriteLine("내 직업이 저들에게는 맘에 들지 않아서 그러는 것이다");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("그럴만하다");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("그야 내 직업은");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("데미지는 세계최강이지만");
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("명중률은 세계최악이기 때문에...");
            Console.ReadLine();
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("■■■  ■■■     ■■");
            Console.WriteLine("■■■■■■■     ■■   ■■  ■■");
            Console.WriteLine("■■■■■■■     ■■   ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■     ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■   ■■  ■■");
            Console.WriteLine("                                     ");
            Console.WriteLine("                     ■■■  ■■■        ■■         ■■      ■■       ");
            Console.WriteLine("                     ■■■■■■■       ■■■        ■■■    ■■          ");
            Console.WriteLine("                     ■■■■■■■     ■■  ■■      ■■■■  ■■          ");
            Console.WriteLine("                     ■■ ■■ ■■    ■■■■■■     ■■  ■■■■             ");
            Console.WriteLine("                     ■■ ■■ ■■   ■■      ■■    ■■    ■■■      ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("                         Loding   □□□□□□□□□□");
            Thread.Sleep(500); //1000 1초 (1000밀리초)
            Console.Clear();    //콘솔 화면 지우기

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("■■■  ■■■     ■■");
            Console.WriteLine("■■■■■■■     ■■   ■■  ■■");
            Console.WriteLine("■■■■■■■     ■■   ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■     ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■   ■■  ■■");
            Console.WriteLine("                                     ");
            Console.WriteLine("                     ■■■  ■■■        ■■         ■■      ■■       ");
            Console.WriteLine("                     ■■■■■■■       ■■■        ■■■    ■■          ");
            Console.WriteLine("                     ■■■■■■■     ■■  ■■      ■■■■  ■■          ");
            Console.WriteLine("                     ■■ ■■ ■■    ■■■■■■     ■■  ■■■■             ");
            Console.WriteLine("                     ■■ ■■ ■■   ■■      ■■    ■■    ■■■      ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("                         Loding.  ■□□□□□□□□□");
            Thread.Sleep(500); //1000 1초 (1000밀리초)
            Console.Clear();    //콘솔 화면 지우기

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("■■■  ■■■     ■■");
            Console.WriteLine("■■■■■■■     ■■   ■■  ■■");
            Console.WriteLine("■■■■■■■     ■■   ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■     ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■   ■■  ■■");
            Console.WriteLine("                                     ");
            Console.WriteLine("                     ■■■  ■■■        ■■         ■■      ■■       ");
            Console.WriteLine("                     ■■■■■■■       ■■■        ■■■    ■■          ");
            Console.WriteLine("                     ■■■■■■■     ■■  ■■      ■■■■  ■■          ");
            Console.WriteLine("                     ■■ ■■ ■■    ■■■■■■     ■■  ■■■■             ");
            Console.WriteLine("                     ■■ ■■ ■■   ■■      ■■    ■■    ■■■      ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("                         Loding.. ■■□□□□□□□□");
            Thread.Sleep(500); //1000 1초 (1000밀리초)
            Console.Clear();    //콘솔 화면 지우기

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("■■■  ■■■     ■■");
            Console.WriteLine("■■■■■■■     ■■   ■■  ■■");
            Console.WriteLine("■■■■■■■     ■■   ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■     ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■   ■■  ■■");
            Console.WriteLine("                                     ");
            Console.WriteLine("                     ■■■  ■■■        ■■         ■■      ■■       ");
            Console.WriteLine("                     ■■■■■■■       ■■■        ■■■    ■■          ");
            Console.WriteLine("                     ■■■■■■■     ■■  ■■      ■■■■  ■■          ");
            Console.WriteLine("                     ■■ ■■ ■■    ■■■■■■     ■■  ■■■■             ");
            Console.WriteLine("                     ■■ ■■ ■■   ■■      ■■    ■■    ■■■      ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("                         Loding   ■■■□□□□□□□");
            Thread.Sleep(500); //1000 1초 (1000밀리초)
            Console.Clear();    //콘솔 화면 지우기

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("■■■  ■■■     ■■");
            Console.WriteLine("■■■■■■■     ■■   ■■  ■■");
            Console.WriteLine("■■■■■■■     ■■   ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■     ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■   ■■  ■■");
            Console.WriteLine("                                     ");
            Console.WriteLine("                     ■■■  ■■■        ■■         ■■      ■■       ");
            Console.WriteLine("                     ■■■■■■■       ■■■        ■■■    ■■          ");
            Console.WriteLine("                     ■■■■■■■     ■■  ■■      ■■■■  ■■          ");
            Console.WriteLine("                     ■■ ■■ ■■    ■■■■■■     ■■  ■■■■             ");
            Console.WriteLine("                     ■■ ■■ ■■   ■■      ■■    ■■    ■■■      ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("                         Loding.  ■■■■□□□□□□");
            Thread.Sleep(500); //1000 1초 (1000밀리초)
            Console.Clear();    //콘솔 화면 지우기

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("■■■  ■■■     ■■");
            Console.WriteLine("■■■■■■■     ■■   ■■  ■■");
            Console.WriteLine("■■■■■■■     ■■   ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■     ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■   ■■  ■■");
            Console.WriteLine("                                     ");
            Console.WriteLine("                     ■■■  ■■■        ■■         ■■      ■■       ");
            Console.WriteLine("                     ■■■■■■■       ■■■        ■■■    ■■          ");
            Console.WriteLine("                     ■■■■■■■     ■■  ■■      ■■■■  ■■          ");
            Console.WriteLine("                     ■■ ■■ ■■    ■■■■■■     ■■  ■■■■             ");
            Console.WriteLine("                     ■■ ■■ ■■   ■■      ■■    ■■    ■■■      ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("                         Loding.. ■■■■■□□□□□");
            Thread.Sleep(500); //1000 1초 (1000밀리초)
            Console.Clear();    //콘솔 화면 지우기

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("■■■  ■■■     ■■");
            Console.WriteLine("■■■■■■■     ■■   ■■  ■■");
            Console.WriteLine("■■■■■■■     ■■   ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■     ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■   ■■  ■■");
            Console.WriteLine("                                     ");
            Console.WriteLine("                     ■■■  ■■■        ■■         ■■      ■■       ");
            Console.WriteLine("                     ■■■■■■■       ■■■        ■■■    ■■          ");
            Console.WriteLine("                     ■■■■■■■     ■■  ■■      ■■■■  ■■          ");
            Console.WriteLine("                     ■■ ■■ ■■    ■■■■■■     ■■  ■■■■             ");
            Console.WriteLine("                     ■■ ■■ ■■   ■■      ■■    ■■    ■■■      ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("                         Loding... ■■■■■■□□□□");
            Thread.Sleep(500); //1000 1초 (1000밀리초)
            Console.Clear();    //콘솔 화면 지우기

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("■■■  ■■■     ■■");
            Console.WriteLine("■■■■■■■     ■■   ■■  ■■");
            Console.WriteLine("■■■■■■■     ■■   ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■     ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■   ■■  ■■");
            Console.WriteLine("                                     ");
            Console.WriteLine("                     ■■■  ■■■        ■■         ■■      ■■       ");
            Console.WriteLine("                     ■■■■■■■       ■■■        ■■■    ■■          ");
            Console.WriteLine("                     ■■■■■■■     ■■  ■■      ■■■■  ■■          ");
            Console.WriteLine("                     ■■ ■■ ■■    ■■■■■■     ■■  ■■■■             ");
            Console.WriteLine("                     ■■ ■■ ■■   ■■      ■■    ■■    ■■■      ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("                         Loding   ■■■■■■■□□□");
            Thread.Sleep(500); //1000 1초 (1000밀리초)
            Console.Clear();    //콘솔 화면 지우기

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("■■■  ■■■     ■■");
            Console.WriteLine("■■■■■■■     ■■   ■■  ■■");
            Console.WriteLine("■■■■■■■     ■■   ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■     ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■   ■■  ■■");
            Console.WriteLine("                                     ");
            Console.WriteLine("                     ■■■  ■■■        ■■         ■■      ■■       ");
            Console.WriteLine("                     ■■■■■■■       ■■■        ■■■    ■■          ");
            Console.WriteLine("                     ■■■■■■■     ■■  ■■      ■■■■  ■■          ");
            Console.WriteLine("                     ■■ ■■ ■■    ■■■■■■     ■■  ■■■■             ");
            Console.WriteLine("                     ■■ ■■ ■■   ■■      ■■    ■■    ■■■      ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("                         Loding.  ■■■■■■■■□□");
            Thread.Sleep(500); //1000 1초 (1000밀리초)
            Console.Clear();    //콘솔 화면 지우기

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("■■■  ■■■     ■■");
            Console.WriteLine("■■■■■■■     ■■   ■■  ■■");
            Console.WriteLine("■■■■■■■     ■■   ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■     ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■   ■■  ■■");
            Console.WriteLine("                                     ");
            Console.WriteLine("                     ■■■  ■■■        ■■         ■■      ■■       ");
            Console.WriteLine("                     ■■■■■■■       ■■■        ■■■    ■■          ");
            Console.WriteLine("                     ■■■■■■■     ■■  ■■      ■■■■  ■■          ");
            Console.WriteLine("                     ■■ ■■ ■■    ■■■■■■     ■■  ■■■■             ");
            Console.WriteLine("                     ■■ ■■ ■■   ■■      ■■    ■■    ■■■      ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("                         Loding.. ■■■■■■■■■□");
            Thread.Sleep(500); //1000 1초 (1000밀리초)
            Console.Clear();    //콘솔 화면 지우기

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("■■■  ■■■     ■■");
            Console.WriteLine("■■■■■■■     ■■   ■■  ■■");
            Console.WriteLine("■■■■■■■     ■■   ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■     ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■   ■■  ■■");
            Console.WriteLine("                                     ");
            Console.WriteLine("                     ■■■  ■■■        ■■         ■■      ■■       ");
            Console.WriteLine("                     ■■■■■■■       ■■■        ■■■    ■■          ");
            Console.WriteLine("                     ■■■■■■■     ■■  ■■      ■■■■  ■■          ");
            Console.WriteLine("                     ■■ ■■ ■■    ■■■■■■     ■■  ■■■■             ");
            Console.WriteLine("                     ■■ ■■ ■■   ■■      ■■    ■■    ■■■      ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("                         Loding... ■■■■■■■■■■");
            Thread.Sleep(500); //1000 1초 (1000밀리초)
            Console.Clear();    //콘솔 화면 지우기

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("■■■  ■■■     ■■");
            Console.WriteLine("■■■■■■■     ■■   ■■  ■■");
            Console.WriteLine("■■■■■■■     ■■   ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■     ■    ■");
            Console.WriteLine("■■ ■■ ■■     ■■   ■■  ■■");
            Console.WriteLine("                                     ");
            Console.WriteLine("                     ■■■  ■■■        ■■         ■■      ■■       ");
            Console.WriteLine("                     ■■■■■■■       ■■■        ■■■    ■■          ");
            Console.WriteLine("                     ■■■■■■■     ■■  ■■      ■■■■  ■■          ");
            Console.WriteLine("                     ■■ ■■ ■■    ■■■■■■     ■■  ■■■■             ");
            Console.WriteLine("                     ■■ ■■ ■■   ■■      ■■    ■■    ■■■      ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("                                  miss     오류로 다시시작 됩니다. ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.ReadLine();
            Console.Clear();
        }
    }
}
